### ISSUE TITLE
compiled

### ISSUE THREAD

**Issue by ourstyle88** [Cruze03/Discord-Utilities-v2#22]
Good afternoon, please tell me what he swears and what he lacks **( SM 1.10 6545 )** ? Steamworks using this - https://github.com/KyleSanderson/SteamWorks 
![123](https://user-images.githubusercontent.com/122776462/212623563-2312853f-c094-4dea-ac5a-7bbdec14eea0.PNG)

**Comment by Cruze03** [comment]
https://github.com/JoinedSenses/SourceMod-IncludeLibrary/blob/master/include/steamworks.inc
