### ISSUE TITLE
Natives AddRole, RemoveRole

### ISSUE THREAD

**Issue by stefanx111** [Cruze03/Discord-Utilities-v2#24]
You will implement natives for addrole and removerole in `du_verification` ?

**Comment by Cruze03** [comment]
[Please have a look at this](https://github.com/Cruze03/Discord-Utilities-v2/blob/add53549d236c2219a64a0869aa3bb5a2a04fb54/scripting/include/discord/DiscordBot.inc#L367)

**Comment by stefanx111** [comment]
I don't really understand how it's supposed to work. Can you give an example.

**Comment by originalaidn** [comment]
If you include the du2:
char sUserId[64];
DUVerification_GetUserId(client, sUserId, sizeof(sUserId);
DUMain_Bot().AddRoleID(sServerId, sUserId, sRoleId);

or if u don't want to use sServerId and sRoleId just use this: //this is RemoveRole
DUMain_Bot().RemoveRoleID("your server id", sUserId, "your role id");

**Comment by stefanx111** [comment]
> If you include the du2: char sUserId[64]; DUVerification_GetUserId(client, sUserId, sizeof(sUserId); DUMain_Bot().AddRoleID(sServerId, sUserId, sRoleId);
> 
> or if u don't want to use sServerId and sRoleId just use this: //this is RemoveRole DUMain_Bot().RemoveRoleID("your server id", sUserId, "your role id");

Solved. 
Thanks!

**Comment by Cruze03** [comment]
@originalaidn thanks ❤️
