### ISSUE TITLE
Corrected Ukrainian translation

### ISSUE THREAD

**Issue by panikajo** [Cruze03/Discord-Utilities-v2#26]
Hello, this is the correct translation, because the current one lacked some functions for displaying the link
was -
`		"ua" 		"Ви також можете {lime} Copy {default}it {orange}in the console{default} :)"
`

now -
		**`"ua" 		"Введіть {lime}{1} {2} {default}на {orange}{3}{default} канал :)"`**
[du_verification.phrases.txt](https://github.com/Cruze03/Discord-Utilities-v2/files/10912312/du_verification.phrases.txt)

**Comment by Cruze03** [comment]
[Thanks! <3](https://github.com/Cruze03/Discord-Utilities-v2/commit/5ee875bc4cff1ba2d3fc7ab4933b62664aea569e)
